server:
  port: 8080

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://localhost:8081
          predicates:
            - Path=/reserves/** 
        - id: confirm
          uri: http://localhost:8082
          predicates:
            - Path=/confirms/**,/cancellations/**
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserves/**
        - id: confirm
          uri: http://confirm:8080
          predicates:
            - Path=/confirms/**,/cancellations/**
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
